### ISSUE TITLE
custom headers configuration on targets is ignored ?

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra-gateway#120]
TIL it was necessary to define globally the headers you want to have, no matter if the configuration is customized for each targets.

For example, considering the following datafeeder configuration:

```
      datafeeder:
        target: ${georchestra.gateway.services.datafeeder.target}
        headers:
          json-user: true
          json-organization: true
```

One could expect the `sec-user` / `sec-organization` json versions of the header to be provided to the datafeeder, but one will also need the following global configuration to actually have them as expected:

```
georchestra:
  gateway:
    default-headers:
      # Default security headers to append to proxied requests
      proxy: true
      username: true
      roles: true
      org: true
      orgname: true
      json-user: true
      json-organization: true
```

At least, we should provide a default datadir configuration which should work with the basic geOrchestra webapps. (e.g. https://github.com/georchestra/datadir/blob/master/gateway/gateway.yaml#L7-L17 to be fixed).
