### ISSUE TITLE
ProConnect - Display and use dedicated button 

### ISSUE THREAD

**Issue by Gaetanbrl** [georchestra/georchestra-gateway#157]
To use ProConnect, a use will need to click on ProConnect button.

![image](https://github.com/user-attachments/assets/083de2f6-9f74-4cee-bd51-20b1bb94b405)

Button details is available here :

https://github.com/numerique-gouv/proconnect-documentation/blob/main/doc_fs/bouton_proconnect.md

**Comment by Gaetanbrl** [comment]
Currently,

Authenntication UI display a standard button :

![image](https://github.com/user-attachments/assets/0db7fd5d-350f-4e27-a251-1aca064ddbdd)

... due to this config (file `gateway/security.yaml`): 

```
georchestra:
  gateway:
    security:
      oauth2:
        enabled: true
...........
spring:
  security:
    oauth2:
      client:
        registration:
          cas-oauth2:
................
```

**Comment by Gaetanbrl** [comment]
Here a config that seems correct (but depends of https://github.com/georchestra/georchestra-gateway/issues/161) :

```
spring:
  security:
    oauth2:
      client:
        registration:
          proconnect:
            client-name: proconnect
            client-id: idtochange
            client-secret: secrettochange
            authorization-grant-type: authorization_code
            redirect-uri: "https://dev.gis.jdev/login"
            scope: openid,siret,email
        provider:
          proconnect:
            authorization-uri: https://fca.integ01.dev-agentconnect.fr/api/v2/authorize
            token-uri: https://fca.integ01.dev-agentconnect.fr/api/v2/token
            user-info-uri: https://fca.integ01.dev-agentconnect.fr/api/v2/userinfo
            end-session-uri: https://fca.integ01.dev-agentconnect.fr/api/v2/session/end
            user-name-attribute: sub
```
