### ISSUE TITLE
PRO/FranceConnect & callback URI

### ISSUE THREAD

**Issue by Gaetanbrl** [georchestra/georchestra-gateway#161]
As part of ProConnect integration,
I get a callback URI error.

Here ma config as expected by the gateway : 

```
spring:
  security:
    oauth2:
      client:
        registration:
          proconnect:
            client-name: proconnect
            client-id: idGivenByProConnect
            client-secret: secretGivenByProConnect
            authorization-grant-type: authorization_code
            redirect-uri: https://dev.jdev.fr/login
            scope: openid,siret,email
        provider:
          proconnect:
            authorization-uri: https://fca.integ01.dev-agentconnect.fr/api/v2/authorize
            token-uri: https://fca.integ01.dev-agentconnect.fr/api/v2/token
            user-info-uri: https://fca.integ01.dev-agentconnect.fr/api/v2/userinfo
            end-session-uri: https://fca.integ01.dev-agentconnect.fr/api/v2/session/end
            user-name-attribute: sub
```

I can't identify if this error is due to the redirect-uri parameter or a compatibility problem with the gateway (or maybe a config trouble between FranceConnect and client-id registration...).

How to get more details from gateway side ?
