### ISSUE TITLE
connexion réussie à proconnect (fr only)

### ISSUE THREAD

**Issue by fphg** [georchestra/georchestra-gateway#194]
J'ai pu réaliser une première connexion au service de test proconnect. j'ai eu du mal à trouver les informations, soit côté doc proconnect, soit du côté doc georchestra. 

Voici un retour pour dev.geobretagne.fr et pour alimenter la doc.

dans démarches simplifiées  https://www.demarches-simplifiees.fr/commencer/demande-creation-fs-fca ::

- Réseau du fournisseur de services : `Internet`
- Environnement du fournisseur de services : `Intégration`
- URLs de redirection de connexion : `https://dev.geobretagne.fr/login/oauth2/code/proconnect`
- Algorithme de signature internet : `HS256`

Vous recevez un mail sous qq jours avec votre identifiant et secret, qui sont appelés tous les deux.... client_id. le plus long est le secret.

dans `datadir/gateway/security.yaml` 

```
spring:
  security:
    oauth2:
      client:
        proconnect:
            provider: proconnect
            client-name: proconnect
            client-authentication-method: post
            client-id: <mettre l'identifiant fourni après instruction DS>
            client-secret: <mettre le secret fourni après instruction DS>
            authorization-grant-type: authorization_code
            redirect-uri: https://dev.geobretagne.fr/login/oauth2/code/proconnect
            scope: openid
        provider:
          proconnect:
            authorization-uri: https://fca.integ01.dev-agentconnect.fr/api/v2/authorize
            token-uri: https://fca.integ01.dev-agentconnect.fr/api/v2/token
            user-info-uri: https://fca.integ01.dev-agentconnect.fr/api/v2/userinfo
            end-session-uri: https://fca.integ01.dev-agentconnect.fr/api/v2/session/end
            jwk-set-uri: https://fca.integ01.dev-agentconnect.fr/api/v2/jwks
            user-name-attribute: sub
```

Ce que je n'ai pas réussi à faire : récupérer les informations utilisateur. Je ne sais pas quelles valeurs entrer pour `scope `et `user-name-attribute`.

Lors des essais sur `https://dev.geobretagne.fr/login` il est utile de surveiller le suivi réseau sur le navigateur, on voit les allers-retour et éventuellement les erreurs. dans mon cas le `redirect-uri` et le `scope `n'étaient pas bons.

**Comment by fphg** [comment]
up, la doc ici est censée expliquer ce qu'il faut mettre dans le scope

https://github.com/numerique-gouv/proconnect-documentation/blob/e7a444fad8346e1b29b2a1dabf86350c50aa0d43/doc_fs/scope-claims.md

**Comment by Gaetanbrl** [comment]
Super @fphg ! 👍 

> j'ai eu du mal à trouver les informations, soit côté doc proconnect, soit du côté doc georchestra

Le problème étant que la doc georchestra ne peut pas expliquer tout le fonctionnement de l'authent et les notions clés (bien que la config soit primairement expliquée).

Pour Proconnect, j'ai du bien lire la [doc officielle](https://github.com/numerique-gouv/proconnect-documentation/blob/main/doc_fs/README.md) qui est assez lourde de base pour appréhender les concepts (techniques ?) de ce type d'authent et enfin pouvoir comprendre la config dans la gateway.

Pour la config des scope (nom de propriété de la config gateway), proConnect parle de scope et claims. C'est en lien avec la [spécification OpenId](https://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims).

Bon, il est vrai qu'on a pas vraiment envie de lire la spec pour configurer une authent dans georchestra...

> Lors des essais sur https://dev.geobretagne.fr/login il est utile de surveiller le suivi réseau sur le navigateur, on voit les allers-retour et éventuellement les erreurs. dans mon cas le redirect-uri et le scope n'étaient pas bons.

Pour ce point on a pas mal galérer avec des aller / retour sur le site des démarches simplifiées afin d'avoir les bonnes URLs. Tout est dit dans ton commentaire, il faut connaître son instance et sinon savoir retrouver les infos.


> j'aimerais bien faire une page de doc sur comment connecter geOr à des auth externe

+1

**Comment by Gaetanbrl** [comment]
@jeanmi151 je me dis qu'une doc en plus type `proconnect_example.adoc` serait pas mal ici :
https://github.com/georchestra/georchestra-gateway/tree/main/docs

**Comment by pmauduit** [comment]
> C'est en lien avec la [spécification OpenId](https://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims).

"openid-connect", pour être pédant (openid v1 étant un protocole existant avant OIDC.

Pour scope et claims, j'avais lu cette page pour appréhender les 2 concepts récemment lors de la mise en place d'un GeoNetwork branché sur leur fournisseur d'identité OIDC: https://curity.io/resources/learn/scopes-vs-claims/

**Comment by fphg** [comment]
@Gaetanbrl +1 pour le readme proconnect qui est un cas particulier openid, ne nécessitant pas de comprendre tout openid pour faire un simple georchestra-proconnect.

côté doc proconnect c'est plus compliqué pour eux d'être compatibles avec x systèmes (et puis c'est le monde du sso qui est décidément cryptique). mais côté georchestra, il y a vraiment pas beaucoup de variables : l'adresse de l'instance suffit

**Comment by Gaetanbrl** [comment]
> Environnement : docker / georchestra 25.0

En complément, je colle ici une configuration pleinement fonctionnelle avec réconciliation par email provider <-> ldap et déconnexion (logout) :

> datadit/gateway/security.yaml

```
georchestra:
  gateway:
    security:
      createNonExistingUsersInLDAP: true
      enableRabbitmqEvents: true
      oauth2:
        enabled: true
      ldap:
        default:
          enabled: true
          extended: true
          url: ldap://${ldapHost:localhost}:${ldapPort:389}/
          baseDn: ${ldapBaseDn:dc=georchestra,dc=org}
          adminDn: ${ldapAdminDn:cn=admin,dc=georchestra,dc=org"}
          adminPassword: ${ldapAdminPassword:secret}
          users:
            rdn: ${ldapUsersRdn:ou=users}
            searchFilter: ${ldapUserSearchFilter:(uid={0})}
            pendingUsersSearchBaseDN: ou=pendingusers
            protectedUsers: geoserver_privileged_user
          roles:
            rdn: ${ldapRolesRdn:ou=roles}
            searchFilter: ${ldapRolesSearchFilter:(member={0})}
          orgs:
            rdn: ${ldapOrgsRdn:ou=orgs}
            protectedRoles: ADMINISTRATOR, GN_.*, ORGADMIN, REFERENT, USER, SUPERUSER
      oidc:
        config:
          provider:
            proconnect:
              searchEmail: true
        claims:
          provider:
            proconnect:
              id.path: "$.sub"
              email.path: "$.email"
              familyName.path: "$.usual_name"
              givenName.path: "$.given_name"
              organization.path: "$.given_name"
              organizationUid.path: "$.siret"
# oauth 2.0
spring:
  security:
    oauth2:
      client:
        registration:
          proconnect:
            provider: proconnect
            client-name: proconnect
            client-authentication-method: client_secret_post
            client-id: id_foo
            client-secret: secret_bar
            authorization-grant-type: authorization_code
            redirect-uri: "https://dev.jdev.fr/login/oauth2/code/proconnect"
            scope: openid,given_name,usual_name,email
        provider:
          proconnect:
            user-name-attribute: sub
            issuer-uri: https://fca.integ01.dev-agentconnect.fr/api/v2
```

Cette configuration fonctionne via grâce une application crée dans https://partenaires.proconnect.gouv.fr/apps (Merci @fphg pour ce bon tuyaux) :

<img width="843" height="702" alt="Image" src="https://github.com/user-attachments/assets/15a79224-29b7-46fd-8e93-6f39a5ebf0b3" />
